/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRespostasRapidasRouteImport } from './routes/_authenticated/respostas-rapidas'
import { Route as AuthenticatedPostagensRouteImport } from './routes/_authenticated/postagens'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedPerfisRouteImport } from './routes/_authenticated/perfis'
import { Route as AuthenticatedPerfilInfluenciadoraRouteImport } from './routes/_authenticated/perfil-influenciadora'
import { Route as AuthenticatedPagamentosRouteImport } from './routes/_authenticated/pagamentos'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedIaRouteImport } from './routes/_authenticated/ia'
import { Route as AuthenticatedHistoriasRouteImport } from './routes/_authenticated/historias'
import { Route as AuthenticatedGruposRouteImport } from './routes/_authenticated/grupos'
import { Route as AuthenticatedFunisRouteImport } from './routes/_authenticated/funis'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConversasRouteImport } from './routes/_authenticated/conversas'
import { Route as AuthenticatedConteudosRouteImport } from './routes/_authenticated/conteudos'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAutomacaoRouteImport } from './routes/_authenticated/automacao'
import { Route as AuthenticatedAssinantesRouteImport } from './routes/_authenticated/assinantes'
import { Route as AuthenticatedPerfisNovoRouteImport } from './routes/_authenticated/perfis.novo'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicScheduledPostsRunRouteImport } from './routes/api/public/scheduled-posts/run'
import { Route as ApiPublicCaktoWebhookRouteImport } from './routes/api/public/cakto/webhook'
import { Route as ApiPublicTelegramWebhookBotIdRouteImport } from './routes/api/public/telegram/webhook.$botId'
import { Route as ApiPublicCaktoWebhookProfileIdRouteImport } from './routes/api/public/cakto/webhook.$profileId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRespostasRapidasRoute =
  AuthenticatedRespostasRapidasRouteImport.update({
    id: '/respostas-rapidas',
    path: '/respostas-rapidas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPostagensRoute = AuthenticatedPostagensRouteImport.update({
  id: '/postagens',
  path: '/postagens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfisRoute = AuthenticatedPerfisRouteImport.update({
  id: '/perfis',
  path: '/perfis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilInfluenciadoraRoute =
  AuthenticatedPerfilInfluenciadoraRouteImport.update({
    id: '/perfil-influenciadora',
    path: '/perfil-influenciadora',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPagamentosRoute = AuthenticatedPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIaRoute = AuthenticatedIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoriasRoute = AuthenticatedHistoriasRouteImport.update({
  id: '/historias',
  path: '/historias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGruposRoute = AuthenticatedGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFunisRoute = AuthenticatedFunisRouteImport.update({
  id: '/funis',
  path: '/funis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConversasRoute = AuthenticatedConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConteudosRoute = AuthenticatedConteudosRouteImport.update({
  id: '/conteudos',
  path: '/conteudos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutomacaoRoute = AuthenticatedAutomacaoRouteImport.update({
  id: '/automacao',
  path: '/automacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssinantesRoute = AuthenticatedAssinantesRouteImport.update({
  id: '/assinantes',
  path: '/assinantes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfisNovoRoute = AuthenticatedPerfisNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AuthenticatedPerfisRoute,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicScheduledPostsRunRoute =
  ApiPublicScheduledPostsRunRouteImport.update({
    id: '/api/public/scheduled-posts/run',
    path: '/api/public/scheduled-posts/run',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCaktoWebhookRoute = ApiPublicCaktoWebhookRouteImport.update({
  id: '/api/public/cakto/webhook',
  path: '/api/public/cakto/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookBotIdRoute =
  ApiPublicTelegramWebhookBotIdRouteImport.update({
    id: '/$botId',
    path: '/$botId',
    getParentRoute: () => ApiPublicTelegramWebhookRoute,
  } as any)
const ApiPublicCaktoWebhookProfileIdRoute =
  ApiPublicCaktoWebhookProfileIdRouteImport.update({
    id: '/$profileId',
    path: '/$profileId',
    getParentRoute: () => ApiPublicCaktoWebhookRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assinantes': typeof AuthenticatedAssinantesRoute
  '/automacao': typeof AuthenticatedAutomacaoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conteudos': typeof AuthenticatedConteudosRoute
  '/conversas': typeof AuthenticatedConversasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/funis': typeof AuthenticatedFunisRoute
  '/grupos': typeof AuthenticatedGruposRoute
  '/historias': typeof AuthenticatedHistoriasRoute
  '/ia': typeof AuthenticatedIaRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/perfil-influenciadora': typeof AuthenticatedPerfilInfluenciadoraRoute
  '/perfis': typeof AuthenticatedPerfisRouteWithChildren
  '/planos': typeof AuthenticatedPlanosRoute
  '/postagens': typeof AuthenticatedPostagensRoute
  '/respostas-rapidas': typeof AuthenticatedRespostasRapidasRoute
  '/perfis/novo': typeof AuthenticatedPerfisNovoRoute
  '/api/public/cakto/webhook': typeof ApiPublicCaktoWebhookRouteWithChildren
  '/api/public/scheduled-posts/run': typeof ApiPublicScheduledPostsRunRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRouteWithChildren
  '/api/public/cakto/webhook/$profileId': typeof ApiPublicCaktoWebhookProfileIdRoute
  '/api/public/telegram/webhook/$botId': typeof ApiPublicTelegramWebhookBotIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assinantes': typeof AuthenticatedAssinantesRoute
  '/automacao': typeof AuthenticatedAutomacaoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conteudos': typeof AuthenticatedConteudosRoute
  '/conversas': typeof AuthenticatedConversasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/funis': typeof AuthenticatedFunisRoute
  '/grupos': typeof AuthenticatedGruposRoute
  '/historias': typeof AuthenticatedHistoriasRoute
  '/ia': typeof AuthenticatedIaRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/perfil-influenciadora': typeof AuthenticatedPerfilInfluenciadoraRoute
  '/perfis': typeof AuthenticatedPerfisRouteWithChildren
  '/planos': typeof AuthenticatedPlanosRoute
  '/postagens': typeof AuthenticatedPostagensRoute
  '/respostas-rapidas': typeof AuthenticatedRespostasRapidasRoute
  '/perfis/novo': typeof AuthenticatedPerfisNovoRoute
  '/api/public/cakto/webhook': typeof ApiPublicCaktoWebhookRouteWithChildren
  '/api/public/scheduled-posts/run': typeof ApiPublicScheduledPostsRunRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRouteWithChildren
  '/api/public/cakto/webhook/$profileId': typeof ApiPublicCaktoWebhookProfileIdRoute
  '/api/public/telegram/webhook/$botId': typeof ApiPublicTelegramWebhookBotIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/assinantes': typeof AuthenticatedAssinantesRoute
  '/_authenticated/automacao': typeof AuthenticatedAutomacaoRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/conteudos': typeof AuthenticatedConteudosRoute
  '/_authenticated/conversas': typeof AuthenticatedConversasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/funis': typeof AuthenticatedFunisRoute
  '/_authenticated/grupos': typeof AuthenticatedGruposRoute
  '/_authenticated/historias': typeof AuthenticatedHistoriasRoute
  '/_authenticated/ia': typeof AuthenticatedIaRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/pagamentos': typeof AuthenticatedPagamentosRoute
  '/_authenticated/perfil-influenciadora': typeof AuthenticatedPerfilInfluenciadoraRoute
  '/_authenticated/perfis': typeof AuthenticatedPerfisRouteWithChildren
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/postagens': typeof AuthenticatedPostagensRoute
  '/_authenticated/respostas-rapidas': typeof AuthenticatedRespostasRapidasRoute
  '/_authenticated/perfis/novo': typeof AuthenticatedPerfisNovoRoute
  '/api/public/cakto/webhook': typeof ApiPublicCaktoWebhookRouteWithChildren
  '/api/public/scheduled-posts/run': typeof ApiPublicScheduledPostsRunRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRouteWithChildren
  '/api/public/cakto/webhook/$profileId': typeof ApiPublicCaktoWebhookProfileIdRoute
  '/api/public/telegram/webhook/$botId': typeof ApiPublicTelegramWebhookBotIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/assinantes'
    | '/automacao'
    | '/configuracoes'
    | '/conteudos'
    | '/conversas'
    | '/dashboard'
    | '/funis'
    | '/grupos'
    | '/historias'
    | '/ia'
    | '/leads'
    | '/pagamentos'
    | '/perfil-influenciadora'
    | '/perfis'
    | '/planos'
    | '/postagens'
    | '/respostas-rapidas'
    | '/perfis/novo'
    | '/api/public/cakto/webhook'
    | '/api/public/scheduled-posts/run'
    | '/api/public/telegram/webhook'
    | '/api/public/cakto/webhook/$profileId'
    | '/api/public/telegram/webhook/$botId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/assinantes'
    | '/automacao'
    | '/configuracoes'
    | '/conteudos'
    | '/conversas'
    | '/dashboard'
    | '/funis'
    | '/grupos'
    | '/historias'
    | '/ia'
    | '/leads'
    | '/pagamentos'
    | '/perfil-influenciadora'
    | '/perfis'
    | '/planos'
    | '/postagens'
    | '/respostas-rapidas'
    | '/perfis/novo'
    | '/api/public/cakto/webhook'
    | '/api/public/scheduled-posts/run'
    | '/api/public/telegram/webhook'
    | '/api/public/cakto/webhook/$profileId'
    | '/api/public/telegram/webhook/$botId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/assinantes'
    | '/_authenticated/automacao'
    | '/_authenticated/configuracoes'
    | '/_authenticated/conteudos'
    | '/_authenticated/conversas'
    | '/_authenticated/dashboard'
    | '/_authenticated/funis'
    | '/_authenticated/grupos'
    | '/_authenticated/historias'
    | '/_authenticated/ia'
    | '/_authenticated/leads'
    | '/_authenticated/pagamentos'
    | '/_authenticated/perfil-influenciadora'
    | '/_authenticated/perfis'
    | '/_authenticated/planos'
    | '/_authenticated/postagens'
    | '/_authenticated/respostas-rapidas'
    | '/_authenticated/perfis/novo'
    | '/api/public/cakto/webhook'
    | '/api/public/scheduled-posts/run'
    | '/api/public/telegram/webhook'
    | '/api/public/cakto/webhook/$profileId'
    | '/api/public/telegram/webhook/$botId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicCaktoWebhookRoute: typeof ApiPublicCaktoWebhookRouteWithChildren
  ApiPublicScheduledPostsRunRoute: typeof ApiPublicScheduledPostsRunRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/respostas-rapidas': {
      id: '/_authenticated/respostas-rapidas'
      path: '/respostas-rapidas'
      fullPath: '/respostas-rapidas'
      preLoaderRoute: typeof AuthenticatedRespostasRapidasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/postagens': {
      id: '/_authenticated/postagens'
      path: '/postagens'
      fullPath: '/postagens'
      preLoaderRoute: typeof AuthenticatedPostagensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfis': {
      id: '/_authenticated/perfis'
      path: '/perfis'
      fullPath: '/perfis'
      preLoaderRoute: typeof AuthenticatedPerfisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil-influenciadora': {
      id: '/_authenticated/perfil-influenciadora'
      path: '/perfil-influenciadora'
      fullPath: '/perfil-influenciadora'
      preLoaderRoute: typeof AuthenticatedPerfilInfluenciadoraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pagamentos': {
      id: '/_authenticated/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof AuthenticatedPagamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ia': {
      id: '/_authenticated/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof AuthenticatedIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historias': {
      id: '/_authenticated/historias'
      path: '/historias'
      fullPath: '/historias'
      preLoaderRoute: typeof AuthenticatedHistoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grupos': {
      id: '/_authenticated/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof AuthenticatedGruposRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funis': {
      id: '/_authenticated/funis'
      path: '/funis'
      fullPath: '/funis'
      preLoaderRoute: typeof AuthenticatedFunisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversas': {
      id: '/_authenticated/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof AuthenticatedConversasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conteudos': {
      id: '/_authenticated/conteudos'
      path: '/conteudos'
      fullPath: '/conteudos'
      preLoaderRoute: typeof AuthenticatedConteudosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automacao': {
      id: '/_authenticated/automacao'
      path: '/automacao'
      fullPath: '/automacao'
      preLoaderRoute: typeof AuthenticatedAutomacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assinantes': {
      id: '/_authenticated/assinantes'
      path: '/assinantes'
      fullPath: '/assinantes'
      preLoaderRoute: typeof AuthenticatedAssinantesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfis/novo': {
      id: '/_authenticated/perfis/novo'
      path: '/novo'
      fullPath: '/perfis/novo'
      preLoaderRoute: typeof AuthenticatedPerfisNovoRouteImport
      parentRoute: typeof AuthenticatedPerfisRoute
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scheduled-posts/run': {
      id: '/api/public/scheduled-posts/run'
      path: '/api/public/scheduled-posts/run'
      fullPath: '/api/public/scheduled-posts/run'
      preLoaderRoute: typeof ApiPublicScheduledPostsRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cakto/webhook': {
      id: '/api/public/cakto/webhook'
      path: '/api/public/cakto/webhook'
      fullPath: '/api/public/cakto/webhook'
      preLoaderRoute: typeof ApiPublicCaktoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook/$botId': {
      id: '/api/public/telegram/webhook/$botId'
      path: '/$botId'
      fullPath: '/api/public/telegram/webhook/$botId'
      preLoaderRoute: typeof ApiPublicTelegramWebhookBotIdRouteImport
      parentRoute: typeof ApiPublicTelegramWebhookRoute
    }
    '/api/public/cakto/webhook/$profileId': {
      id: '/api/public/cakto/webhook/$profileId'
      path: '/$profileId'
      fullPath: '/api/public/cakto/webhook/$profileId'
      preLoaderRoute: typeof ApiPublicCaktoWebhookProfileIdRouteImport
      parentRoute: typeof ApiPublicCaktoWebhookRoute
    }
  }
}

interface AuthenticatedPerfisRouteChildren {
  AuthenticatedPerfisNovoRoute: typeof AuthenticatedPerfisNovoRoute
}

const AuthenticatedPerfisRouteChildren: AuthenticatedPerfisRouteChildren = {
  AuthenticatedPerfisNovoRoute: AuthenticatedPerfisNovoRoute,
}

const AuthenticatedPerfisRouteWithChildren =
  AuthenticatedPerfisRoute._addFileChildren(AuthenticatedPerfisRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssinantesRoute: typeof AuthenticatedAssinantesRoute
  AuthenticatedAutomacaoRoute: typeof AuthenticatedAutomacaoRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedConteudosRoute: typeof AuthenticatedConteudosRoute
  AuthenticatedConversasRoute: typeof AuthenticatedConversasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFunisRoute: typeof AuthenticatedFunisRoute
  AuthenticatedGruposRoute: typeof AuthenticatedGruposRoute
  AuthenticatedHistoriasRoute: typeof AuthenticatedHistoriasRoute
  AuthenticatedIaRoute: typeof AuthenticatedIaRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedPagamentosRoute: typeof AuthenticatedPagamentosRoute
  AuthenticatedPerfilInfluenciadoraRoute: typeof AuthenticatedPerfilInfluenciadoraRoute
  AuthenticatedPerfisRoute: typeof AuthenticatedPerfisRouteWithChildren
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedPostagensRoute: typeof AuthenticatedPostagensRoute
  AuthenticatedRespostasRapidasRoute: typeof AuthenticatedRespostasRapidasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssinantesRoute: AuthenticatedAssinantesRoute,
  AuthenticatedAutomacaoRoute: AuthenticatedAutomacaoRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedConteudosRoute: AuthenticatedConteudosRoute,
  AuthenticatedConversasRoute: AuthenticatedConversasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFunisRoute: AuthenticatedFunisRoute,
  AuthenticatedGruposRoute: AuthenticatedGruposRoute,
  AuthenticatedHistoriasRoute: AuthenticatedHistoriasRoute,
  AuthenticatedIaRoute: AuthenticatedIaRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedPagamentosRoute: AuthenticatedPagamentosRoute,
  AuthenticatedPerfilInfluenciadoraRoute:
    AuthenticatedPerfilInfluenciadoraRoute,
  AuthenticatedPerfisRoute: AuthenticatedPerfisRouteWithChildren,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedPostagensRoute: AuthenticatedPostagensRoute,
  AuthenticatedRespostasRapidasRoute: AuthenticatedRespostasRapidasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicCaktoWebhookRouteChildren {
  ApiPublicCaktoWebhookProfileIdRoute: typeof ApiPublicCaktoWebhookProfileIdRoute
}

const ApiPublicCaktoWebhookRouteChildren: ApiPublicCaktoWebhookRouteChildren = {
  ApiPublicCaktoWebhookProfileIdRoute: ApiPublicCaktoWebhookProfileIdRoute,
}

const ApiPublicCaktoWebhookRouteWithChildren =
  ApiPublicCaktoWebhookRoute._addFileChildren(
    ApiPublicCaktoWebhookRouteChildren,
  )

interface ApiPublicTelegramWebhookRouteChildren {
  ApiPublicTelegramWebhookBotIdRoute: typeof ApiPublicTelegramWebhookBotIdRoute
}

const ApiPublicTelegramWebhookRouteChildren: ApiPublicTelegramWebhookRouteChildren =
  {
    ApiPublicTelegramWebhookBotIdRoute: ApiPublicTelegramWebhookBotIdRoute,
  }

const ApiPublicTelegramWebhookRouteWithChildren =
  ApiPublicTelegramWebhookRoute._addFileChildren(
    ApiPublicTelegramWebhookRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicCaktoWebhookRoute: ApiPublicCaktoWebhookRouteWithChildren,
  ApiPublicScheduledPostsRunRoute: ApiPublicScheduledPostsRunRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
